// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PartsTracker.Modules.Parts.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class SeedParts : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                INSERT INTO parts.parts (part_number, description, quantity_on_hand, location_code, is_deleted) VALUES
                ('PRT-000001', 'Brake Pad - High performance ceramic brake pad', 50, 'LOC-001', FALSE),
                ('PRT-000002', 'Oil Filter - Synthetic oil filter for extended engine life', 45, 'LOC-001', FALSE),
                ('PRT-000003', 'Spark Plug - Iridium spark plug for improved ignition', 40, 'LOC-001', FALSE);
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
