name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/server/Api/PartsTracker.Api/PartsTracker.Api.csproj

      - name: Restore dependencies (Web)
        run: dotnet restore src/server/Web/PartsTracker.Web/PartsTracker.Web.csproj

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Build PartsTracker.Api Docker image
        run: docker build -t partstracker-api:latest src/server/Api/PartsTracker.Api

      - name: Build PartsTracker.Web Docker image
        run: docker build -t partstracker-web:latest src/server/Web/PartsTracker.Web